version: "2"
services:
    db:
        container_name: db
        image: mariadb:latest
        ports:
            - "3306:3306"
        environment:
            MARIADB_DATABASE: test
            MARIADB_USER: user
            MARIADB_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - './db_vol:/var/lib/mysql'
            - './db_conf:/etc/mysql' # nothing here atm
    php:
        container_name: admin
        image: phpmyadmin:latest
        links:
            - db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
    lb:
        image: haproxy
        ports:
            - "8080:8080"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
    nodeapp1:
        container_name: n1
        image: nodeapp
        ports:
            - 1111:1111
        environment:
            - APPID=1111
        depends_on:
            - db
            - php
    nodeapp2:
        container_name: n2
        image: nodeapp
        ports:
            - 2222:2222
        environment:
            - APPID=2222
        depends_on:
            - db
            - php
    nodeapp3:
        container_name: n3
        image: nodeapp
        ports:
            - 3333:3333
        environment:
            - APPID=3333
        depends_on:
            - db
            - php